version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped

    ports:
      # jenkins default port
      - "8080:8080"
      # this port is used to connect Jenkins agents, specially used on master.slave mode to distribute the work charge
      - "50000:50000"

    #environment:
    # variable use for JVM options and in this case the value disable the Jenkins initial configuration wizard
    #- JAVA_OPTS=-Djenkins.install.runSetupWizard=false

    volumes:
      - jenkins_home:/var/jenkins_home

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - NET_RAW

    # opcional: limita recursos
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1g

volumes:
  jenkins_home:

# Running
#   docker pull jenkins/jenkins
#   docker compose up -d
#   docker compose -f docker-compose.yml up -d
# enter to the container
#   docker exec -it jenkins bash
# check the password and copy
#   cat /var/jenkins_home/secrets/initialAdminPassword
# when make changes on Dockerfile or docker-compose.yml you must rebuild the image
# docker compose up -d --build --force-recreate

